[workspace]

members = [
    "libmyrtle",
    "myrtle-rp2040",
    "myrtle-rpi",
    "myrtle-cli"
]

resolver = "2"

[profile.release]
codegen-units = 1
debug = 2
strip = true
debug-assertions = false
incremental = false
lto = true
opt-level = 0
overflow-checks = false
