[package]
name = "libmyrtle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop = "0.20.0"
mockall = "0.11.4"
nom = "7.1.3"

[build-dependencies]
lalrpop = "0.20.0"
