[package]
name = "liblink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
ringbuffer = "0.13.0"

[lib]
name = "liblink"
path = "lib.rs"
